import React from "react";
import { Section } from "@/components/Section";
import { GMAIL_COMPOSE_URL } from "@/lib/constants";

export const metadata = {
  title: "Terms of Service — The Gravity Studios",
  description: "Terms of Service for The Gravity Studios website and services.",
};

export default function TermsOfServicePage() {
  return (
    <div className="flex flex-col min-h-screen pt-28 sm:pt-36 pb-24 select-text">
      <Section className="w-full">
        <div className="max-w-3xl mx-auto px-6 sm:px-8 text-left">
          {/* PAGE TITLE */}
          <h1 className="text-3xl sm:text-5xl font-headline font-bold text-[var(--text-primary)] tracking-tight mb-3">
            Terms of Service
          </h1>

          {/* LAST UPDATED DATE */}
          <p className="text-sm font-mono text-[var(--text-muted)] mb-10 pb-6 border-b border-[var(--border-color)]">
            Last updated: August 28, 2026
          </p>

          {/* BODY CONTENT */}
          <div className="space-y-6 text-sm sm:text-base text-[var(--text-muted)] leading-relaxed font-sans">
            <p>
              These Terms of Service govern your use of thegravitystudios.com, operated by The Gravity Studios, a sole proprietorship of Prameet Patani. By using this site, you agree to these terms.
            </p>

            <h2 className="text-xl sm:text-2xl font-headline font-bold text-[var(--text-primary)] pt-4">
              Use of the Site
            </h2>
            <p>
              This site is provided for informational purposes to showcase our work and services and to allow prospective clients to get in touch. You agree not to misuse the site, attempt to gain unauthorized access to it, or use it for any unlawful purpose.
            </p>

            <h2 className="text-xl sm:text-2xl font-headline font-bold text-[var(--text-primary)] pt-4">
              Intellectual Property
            </h2>
            <p>
              All content on this site — including but not limited to text, images, video, logos, and the Gravity Studios name and visual identity — is the property of The Gravity Studios or its licensors and is protected by applicable intellectual property laws. Nothing on this site grants you a license to use our content, brand assets, or work samples without our prior written permission.
            </p>

            <h2 className="text-xl sm:text-2xl font-headline font-bold text-[var(--text-primary)] pt-4">
              The Build Your Base Strategy Tool
            </h2>
            <p>
              The output generated by this tool is a general, illustrative starting point based on the information you provide and is not a formal proposal, quote, or guarantee of results. A real engagement begins with a discovery call.
            </p>

            <h2 className="text-xl sm:text-2xl font-headline font-bold text-[var(--text-primary)] pt-4">
              No Guarantee of Outcomes
            </h2>
            <p>
              Any examples, case studies, or results referenced on this site reflect specific past engagements and are not a guarantee of similar results for any other brand.
            </p>

            <h2 className="text-xl sm:text-2xl font-headline font-bold text-[var(--text-primary)] pt-4">
              Engagements
            </h2>
            <p>
              These Terms govern use of the website only. Any actual creative or production engagement with The Gravity Studios is governed by a separate signed agreement between the client and The Gravity Studios, which sets out scope, fees, timelines, and intellectual property terms for that specific project.
            </p>

            <h2 className="text-xl sm:text-2xl font-headline font-bold text-[var(--text-primary)] pt-4">
              Governing Law
            </h2>
            <p>
              These Terms are governed by the laws of India, and any disputes are subject to the exclusive jurisdiction of the courts of Mumbai, India, except where a separately signed client agreement specifies otherwise for that engagement.
            </p>

            <h2 className="text-xl sm:text-2xl font-headline font-bold text-[var(--text-primary)] pt-4">
              Limitation of Liability
            </h2>
            <p>
              The site and its content are provided &quot;as is.&quot; To the fullest extent permitted by law, The Gravity Studios is not liable for any indirect, incidental, or consequential damages arising from your use of this site.
            </p>

            <h2 className="text-xl sm:text-2xl font-headline font-bold text-[var(--text-primary)] pt-4">
              Changes to These Terms
            </h2>
            <p>
              We may update these Terms from time to time. Continued use of the site after changes constitutes acceptance of the updated Terms.
            </p>

            <h2 className="text-xl sm:text-2xl font-headline font-bold text-[var(--text-primary)] pt-4">
              Contact
            </h2>
            <p>
              <a href={GMAIL_COMPOSE_URL} target="_blank" rel="noreferrer" className="text-[var(--text-primary)] underline underline-offset-4 hover:text-purple-400">
                business@thegravitystudios.com
              </a>
            </p>
          </div>
        </div>
      </Section>
    </div>
  );
}
